engines:
 duplication:
  enabled: true
  config:
    languages:
      javascript:
        mass_threshold: 50
 eslint:
  enabled: true
  channel: "eslint-2"

ratings:
 paths:
 - "**.js"

exclude_paths:
